spring:
  application:
    name: firstApp
  datasource:
    url: jdbc:postgresql://localhost:5434/mydb
    username: user
    password: user
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
