spring:
  application:
    name: firstApp

  datasource:
    url: jdbc:postgresql://localhost:5434/mydb
    username: user
    password: user
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false        # Désactive l'auto-commit au niveau du pool HikariCP

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        connection:
          provider_disables_autocommit: true  # Désactive l'auto-commit pour la gestion des LOBs par Hibernate

  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

rasa:
  url: http://localhost:5006
