language: en

pipeline:
- name: WhitespaceTokenizer

  # optional but can help general regex-based features
- name: RegexFeaturizer

  # this one actually fires on your lookup file
- name: RegexEntityExtractor
    # if you want to match literal `[intermediate](level)`
    # you can rely on your lookup file instead of hand-coding patterns:
  use_lookup: true

  # you can also add a CRF extractor if you like (more statistical):
  # - name: CRFEntityExtractor

- name: CountVectorsFeaturizer

- name: DIETClassifier
  epochs: 100
    # tell DIET to also predict your 'level' entity
  entity_recognition: true

- name: EntitySynonymMapper

- name: FallbackClassifier
  threshold: 0.3
  ambiguity_threshold: 0.1

policies:
- name: MemoizationPolicy
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: action_default_fallback
  enable_fallback_prediction: true
assistant_id: 20250610-144134-sunny-objective
